In [32]:
import cv2
import numpy as np
import os

def log(c,img):
    normalized_img = img/np.max(img)
    transformed_img = c*np.log(1+normalized_img)
    output = transformed_img/np.max(transformed_img)#np.uint8(transfromed_img*255)
    return output

def gamma(c,img,gamma):
    lut = np.zeros(256,dtype=np.float32)
    for i in range(256):
        lut[i] = c*np.power(i,gamma)
    output = cv2.LUT(img,lut)
    output = np.uint8(output+0.5)
    return output

img = cv2.imdecode(np.fromfile("D:/Lab/ultrasound PTB/data/data1/images/healthy/白锋_0_4.9.jpg", dtype=np.uint8), -1)
output = log(10,img)
cv2.imshow("input",img)
cv2.imshow("output",output)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[[  1.98872889   3.97754515   4.97198562]
  [  0.           0.           0.99435344]
  [  0.           1.98872889   2.98312618]
  ...
  [  5.96644744   0.           5.96644744]
  [  8.94995932   0.           5.96644744]
  [  6.96093044   0.           3.97754515]]

 [[  0.           2.98312618   7.95543445]
  [  0.           2.98312618   5.96644744]
  [  0.           0.99435344   5.96644744]
  ...
  [  0.99435344   0.           6.96093044]
  [  4.97198562   0.           6.96093044]
  [  9.94450489   1.98872889  11.93365751]]

 [[170.25964382 179.22948185 189.19669191]
  [173.2495196  182.21956638 191.19022242]
  [170.25964382 180.22616911 190.19345354]
  ...
  [177.23613022 180.22616911 194.18057225]
  [181.22286397 181.22286397 195.17736981]
  [186.20645088 186.20645088 200.16146342]]

 ...

 [[ 14.91753784  19.89106563  18.89632135]
  [  8.94995932  13.92289107  12.92826425]
  [ 13.92289107  15.9122044   15.9122044 ]
  ...
  [ 20.88582898  12.92826425  13.92289107]
  [ 18.89632135  1